### ISSUE TITLE
Need to add coverage of portability/substitutability

### ISSUE THREAD

**Issue by kimdhamilton** [w3c-ccg/did-use-cases#10]
From CCG mailing list https://lists.w3.org/Archives/Public/public-credentials/2019Apr/0119.html, @jandrieu's last response. We need to add coverage in this doc.

> I believe that if you look at the DID Use Cases document, https://w3c-ccg.github.io/did-use-cases/, in the requirements section you'll see a lot of points related to survivability, but not necessarily portability/substitutability. There are some that are close, but it isn't obvious. That's probably an oversight.

> In the VC use case driven requirements https://w3c.github.io/vc-data-model/#use-cases-and-requirements, we were explicit about the need for the holder's freedom to use any agent software they like. 

> Holders can interact with any issuer and any verifier through any user agent.

> The verifiability is NOT dependent on the wallet. 

> We really should include that requirement in the DID work. The math and the network are what relying parties should be checking for. The truth is, you can NEVER trust the client/user-agent. That's the whole point of keys and DLTs, they provide a way around that.

> So I would go further than Drummond and suggest that we advocate for interoperability requirements that prevent white-listing specific instances of software. IMO, that way lies madness.

> The current approach is parallel to the data model & syntax approach of VCs, so we can't require that any given software do anything in particular, but we can require that the data model and resulting capabilities must work, regardless of which agent is performing the related step.

**Comment by darrellodonnell** [comment]
> So I would go further than Drummond and suggest that we advocate for interoperability requirements that prevent white-listing specific instances of software. IMO, that way lies madness.

I fully disagree with this concept. Whitelists are required. I'll give a simple example:

- How am I to know that my "digital wallet" isn't sending information to a state actor (i.e. that isn't good/required)? The only feasible way that I can think of to protect consumers here is to create a certification regime, which implies formal whitelists. 

At CULedger we will most certainly be maintaining a whitelist of authorized/accepted digital wallets.

**Comment by jandrieu** [comment]
We've adopted this issue over at the DIDWG use cases document. Closing here.
