### ISSUE TITLE
FYI: Indy has an early, early beginnings of a use case document...

### ISSUE THREAD

**Issue by mwherman2000** [w3c-ccg/did-use-cases#2]
Indy has an early, early beginnings of a use case document...
https://docs.google.com/document/d/1EMiqzdd-6TB2puzamDGJSLrDTwUz_QW46xdEp2FLnbI/edit

Currently, it's a list of potential use cases by name.

CC: @msporny

**Comment by jandrieu** [comment]
We reviewed the document. Thanks for the input.
