### ISSUE TITLE
Time Stamp Proofs

### ISSUE THREAD

**Issue by ChristopherA** [w3c-ccg/did-use-cases#3]
For long-term credentials, for instance in the Educational use case, the fact that  most DIDs include strong time stamps, that Verifiable Credentials can also do them as well, as well as some status/revocation also do, means that you can make statements that the claim was valid when issued and for a period of time. Even if the issuer disappears or rotates their own keys, this may be sufficient to validate the DID & Credentials in some scenarios.

**Comment by jandrieu** [comment]
Are you suggesting this as a Feature?  The feature that maybe fits in that is auditability.

We have "audit" as an action, but we don't list it as a feature. Auditing would include checking a timestamp. Is that where you're heading?

**Comment by ChristopherA** [comment]
I think the whole category of auditing and being able to prove statements to third-parties (such as a court) after-the-fact is an interesting feature category. The identity equivalent of sophisticated cryptography like "proof of reserves" and various zkp range and scalar proofs.

**Comment by ChristopherA** [comment]
Specific to the a long-term credential, without a time-stamp I don't think it can be long-term. Most hash-based proofs, and in particular Merkle-proofs are quantum resistant. Thus I can be fairly certain in 2070 that a certificate presented to me from a prospective employee  in 2030 (or in a land title related claim that a loan was paid off) that even though the crypto signature could be broken by a quantum computer in 2070, the time-stamp was valid in, thus the proof is reasonably valid.

**Comment by jandrieu** [comment]
This will be moved over to the DIDWG use cases document. Once we add it, we'll close this issue here.

**Comment by jandrieu** [comment]
Moved. Closing.
