### ISSUE TITLE
did-spec: 10 design goals

### ISSUE THREAD

**Issue by mwherman2000** [w3c-ccg/did-use-cases#5]
RE: https://w3c-ccg.github.io/did-spec/#design-goals

Anticipating the obvious question: what is the relationship between the 10 design goals in the did-spec and the list of features, benefits, etc. in the use case document?

**Comment by jandrieu** [comment]
They are independent. The features were distilled from the last several months of discussion, especially starting with TPAC and then the weekly CCG calls. The features are distinguishing features of DIDs, especially taken together. The goals, as written, include things like "Privacy" and "Simplicity" which are fine goals, but don't distinguish DIDs from other identity systems.

**Comment by jandrieu** [comment]
My response seems to have addressed @mwherman2000's question. Closing.
