### ISSUE TITLE
Position/differentiate DIDs and DID Documents (and the DID Resolution protocol) relative to existing Internet concepts and protocols

### ISSUE THREAD

**Issue by mwherman2000** [w3c-ccg/did-use-cases#6]
One suggestion for improving the Use Cases document is to have it position/differentiate DIDs and DID Documents (and the DID Resolution protocol) relative to existing Internet concepts and protocols ...for example, something like:
https://github.com/mwherman2000/indy-arm/blob/master/README.md#appendix-c---internet-naming-continuum

**Comment by jandrieu** [comment]
This will be moved to the DID WG general issues list for consideration as a separate note that highlights DIDs v alternative identifier systems. Once added, we'll close it here.

**Comment by jandrieu** [comment]
Closing.
